version: '3.3'
services:
  gateway:
    restart: unless-stopped
    build: .
    environment:
      - "CODO_GATEWAY.admin.accounts=cctest"
      - "CODO_GATEWAY.appName=cctest_api-gateway"
      - "CODO_GATEWAY.env=cctest_test"
      - "CODO_GATEWAY.etcd.http_host=http://127.0.0.1:2379"
      - "CODO_GATEWAY.etcd.data_prefix=/my/gw/cctest"
      - "CODO_GATEWAY.jwt_auth.key=cctest_auth_key"
      - "CODO_GATEWAY.jwt_auth.token_secret=cctest_xxxxx"
      - "CODO_GATEWAY.codo_rbac.key=cctest_auth_key"
      - "CODO_GATEWAY.codo_rbac.token_secret=cctest_xxxx"
      - "CODO_GATEWAY.sso2internal.sso_token_secret=cctest_xxxxxx"
      - "CODO_GATEWAY.sso2internal.sso_jwt_key=cctest_sso_token"
      - "CODO_GATEWAY.sso2internal.internal_token_secret=cctest_xxxx"
      - "CODO_GATEWAY.sso2internal.internal_jwt_key=cctest_auth_key"
      - "CODO_GATEWAY.mfa.mfa_secret=cctest_xxxxxx"
      - "CODO_GATEWAY.mfa.mfa_key=cctest_mfa_key"
      - "CODO_GATEWAY.plugins_config.redis-logger.host=127.0.0.2"
      - "CODO_GATEWAY.plugins_config.redis-logger.port=6379"
      - "CODO_GATEWAY.plugins_config.redis-logger.auth_pwd=1234567"
      - "CODO_GATEWAY.plugins_config.redis-logger.db=2"
      - "CODO_GATEWAY.plugins_config.redis-logger.alive_time=604801"
      - "CODO_GATEWAY.plugins_config.redis-logger.channel=cctest_gw"
      - "CODO_GATEWAY.plugins_config.redis-logger.full_log=cctest_no"
      - "CODO_GATEWAY.admin.jwt_secret=cctest_xxxxx"
      - "CODO_GATEWAY.admin.account.admin.password=cctest_tainiubile"
      - "CODO_GATEWAY.admin.account.admin.info.introduction=cctest_I am a super administrator"
      - "CODO_GATEWAY.admin.account.admin.info.avatar=https://wpimg.wallstcn.com/f778738c-e4f8-4870-b634-56703b4acafecctest.gif"
      - "CODO_GATEWAY.admin.account.admin.info.name=cctest_管理员"
      - "CODO_GATEWAY.tokens=e09d6153f1c15395397be3639d14479"
      - "CODO_GATEWAY.plugins=default_plugin,discovery_plugin,tracing_plugin,rewrite_plugin,jwt_plugin,codo_rbac_plugin,kafka-logger,redis-logger,limit-req,referer-restriction,ip-restriction,cors_plugin,sso2internal"
    ports:
      - "8888:8888"
      - "11000:11000"
